name: Build and test with Java CI and Maven

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  release:
    name: Build, test, and publish to GitHub repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup the Java version
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'

      # Build and run tests
      - name: Maven package
        run: |
          mvn package